# Generated by Django 2.2.6 on 2019-11-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
            ],
            options={
                'verbose_name_plural': 'Kategóriák',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cím')),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.TextField()),
                ('uploded', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Photos.Category')),
            ],
            options={
                'verbose_name_plural': 'Fotók',
            },
        ),
    ]
