# Generated by Django 2.2.6 on 2019-11-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0002_auto_20191028_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Képek'},
        ),
    ]
