# Generated by Django 2.2.7 on 2019-11-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0003_auto_20191116_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Név'),
        ),
    ]
